### ISSUE TITLE
use python scripts with boto3 instead of shell scripts and aws cli directly

### ISSUE THREAD

**Issue by michaeldiender-shinesolutions** [shinesolutions/aem-aws-stack-provisioner#42] opened 2017-06-05 06:58 UTC
enter-standby.sh and exit-standby.sh:

http://boto3.readthedocs.io/en/latest/reference/services/autoscaling.html

stack-offline-compaction-snapshot.sh.epp and stack-offline-snapshot.sh.epp:

http://boto3.readthedocs.io/en/latest/reference/services/sns.html#SNS.Client.publish

**Comment by cliffano** [comment] 2017-12-05 01:08
Closing this ticket, it's a duplicate of #6.

**Closed by cliffano** 2017-12-05 01:08 UTC
Labels: duplicate
